### PR TITLE
Store DSL.

### PR DESCRIPTION
**Pull request by Tapchicoma**
Provides fluent store DSL:

TBA

### CODE REVIEW

**Comment by Tapchicoma** [comment]
Added initial store DSL and reducer DSL itself:
```kotlin
sealed class States {
    object Initial : States()
    object LoadingFirst : States()
    data class First(val one: Int) : States()
    data class Second(val another: String) : States()
}

sealed class Actions {
    object LoadFirst : Actions()
    data class FirstLoaded(val data: Int) : Actions()
    object LoadSecond : Actions()
    data class SecondLoaded(val data: String) : Actions()
}

runBlocking {
    val store = describeStore<States, Actions>("test store") {
        enableLogging(listOf(TimberLogSink()))
        startImmediately()

        reducer {
            withInitialState(States.Initial)

            onState<States.Initial>() produce { _, _ -> States.LoadingFirst }
            onState<States.LoadingFirst>() and onAction<Actions.FirstLoaded>() produce { _, action -> States.First(action.data) }
            onState<States.First> { it.one == 10 } and onAction<Actions.LoadSecond>() produce { state, _ -> States.Second(state.one.toString()) }
        }

        sideEffects {
            // To be added
        }
    }

    store.subscribe { println("state: $it") }
}
```

Considering:
- move name from `describeStore()` to `name()` method inside
- allow to describe reducer condition starting with `onAction()` - this will mean on _any_ state.
- possibly introduce some `operator` functions in reducer dsl
- replace `enableLogging()` with `withLogger(logSink)`

@sockeqwe @fraherm would be nice if you will take a look on it and provide general feedback on how this DSL currently looking.

**Comment by befrvnk** [comment]
@Tapchicoma I like it a lot! 💯 Especially the connection between states and actions. This makes it easier to understand the flow of the state machine.

**Comment by sockeqwe** [comment]
For the reducer, do we need a `onAction()` only?

```
 reducer {
            withInitialState(States.Initial)

            OnAction<Actions.LoadSecond>() produce { action,  _ -> ... }
  
        }
```

**Comment by Tapchicoma** [comment]
> For the reducer, do we need a onAction() only?

I think yes - that can be a case on _any state and_ onAction(), where _any state and_ is omitted.

**Pull request closed without merging**
